name: Publish Package

on:
  pull_request:
    branches: [master]
    types: [closed]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_PACKAGE_SHARED_PAT }}

      - name: Git setup
        run: |
          git config --global user.name "tvenegas10"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.0.0

      - name: Install Dependencies
        run: npm install

      - name: Version bump and publish
        run: |
          npm package:release
          git push --follow-tags origin master
          npm package:publish
