name: PR Title Check

on:
  pull_request:
    types: [opened, reopened, edited]

env:
  NODE_AUTH_TOKEN: ${{ secrets.CLIENT_ENGINEERING_GA_SHARED_PAT }}
  STORYBOOK_MAP_TOKEN: ${{ secrets.GOOGLE_MAP_API_KEY }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Title
        run: echo "${{github.event.pull_request.title}}" | npx commitlint
